# Generated by Django 2.2 on 2019-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0002_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter_page',
            old_name='image_seccion1',
            new_name='background_color_image',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='border_image_seccion1',
            new_name='background_color_title1',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='border_radius_image_seccion1',
            new_name='blur_text_shadow',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='caracteristicas_title',
            new_name='border_image_seccion2',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='height_image_seccion1',
            new_name='border_radius_image_seccion2',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='padding_image_seccion1',
            new_name='border_radius_title1',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='planes_title',
            new_name='color_descripcion1',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='seccion1_title',
            new_name='color_text_shadow',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='width_image_seccion1',
            new_name='color_title1',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='description_caracteristicas',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='description_planes',
            new_name='description_seccion2',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='description_seccion1',
            new_name='seccion3_description',
        ),
        migrations.RenameField(
            model_name='counter_page',
            old_name='description_title1',
            new_name='seccion4_decription',
        ),
        migrations.AddField(
            model_name='counter_page',
            name='background_repeat',
            field=models.ImageField(default=1, upload_to='static/img/images_counter/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='height_image_seccion2',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='horizontal_text_shadow',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='image_seccion2',
            field=models.ImageField(default=1, upload_to='static/img/images_counter/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='padding_image_seccion2',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='padding_titles',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='seccion2_title',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='seccion3_title',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='seccion4_title',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='text_aling_paragrafos',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='text_aling_titles',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='title_pestana',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='vertical_text_shadow',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='width_image_seccion2',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter_page',
            name='width_logo',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
