# Generated by Django 2.2 on 2019-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0003_auto_20190426_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter_page',
            name='background_color_page',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
