# Generated by Django 2.2 on 2019-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0004_counter_page_background_color_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracterist',
            new_name='Caracteristicas',
        ),
        migrations.AddField(
            model_name='counter_page',
            name='for_page',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
