# Generated by Django 2.2 on 2019-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0006_auto_20190427_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicas',
            name='background_color_contenedor',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='background_color_contenedor',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
