# Generated by Django 2.2 on 2019-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0007_auto_20190427_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicas',
            name='height_contenedor',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='height_contenedor',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
