# Generated by Django 2.2 on 2019-04-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0008_auto_20190427_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter_page',
            old_name='seccion4_decription',
            new_name='seccion4_description',
        ),
    ]
