# Generated by Django 2.2 on 2019-04-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0009_auto_20190427_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='static/img/favicon/')),
                ('title_pestana', models.CharField(max_length=90)),
                ('logo', models.ImageField(upload_to='static/img/logo/')),
                ('width_logo', models.CharField(max_length=90)),
                ('background_color_page', models.CharField(max_length=90)),
                ('font_family_titles', models.CharField(max_length=90)),
                ('font_sizes_titles', models.CharField(max_length=90)),
                ('background_color_titles', models.CharField(max_length=90)),
                ('color_titles', models.CharField(max_length=90)),
                ('width_titles', models.CharField(max_length=90)),
                ('height_titles', models.CharField(max_length=90)),
                ('padding_titles', models.CharField(max_length=90)),
                ('text_aling_titles', models.CharField(max_length=90)),
                ('border_titles', models.CharField(max_length=90)),
                ('border_radius_titles', models.CharField(max_length=90)),
                ('font_family_paragrafos', models.CharField(max_length=90)),
                ('font_sizes_paragrafos', models.CharField(max_length=90)),
                ('background_color_paragrafos', models.CharField(max_length=90)),
                ('color_paragrafos', models.CharField(max_length=90)),
                ('width_paragrafos', models.CharField(max_length=90)),
                ('text_aling_paragrafos', models.CharField(max_length=90)),
                ('height_paragrafos', models.CharField(max_length=90)),
                ('border_paragrafos', models.CharField(max_length=90)),
                ('border_radius_paragrafos', models.CharField(max_length=90)),
                ('title1', models.CharField(max_length=90)),
                ('color_title1', models.CharField(max_length=90)),
                ('background_color_title1', models.CharField(max_length=90)),
                ('border_radius_title1', models.CharField(max_length=90)),
                ('horizontal_text_shadow', models.CharField(max_length=90)),
                ('vertical_text_shadow', models.CharField(max_length=90)),
                ('blur_text_shadow', models.CharField(max_length=90)),
                ('color_text_shadow', models.CharField(max_length=90)),
                ('image_title1', models.ImageField(upload_to='static/img/images_counter/')),
                ('background_color_image', models.ImageField(upload_to='static/img/images_counter/')),
                ('background_repeat', models.ImageField(upload_to='static/img/images_counter/')),
                ('description1', models.CharField(max_length=9000)),
                ('color_descripcion1', models.CharField(max_length=90)),
                ('seccion2_title', models.CharField(max_length=90)),
                ('image_seccion2', models.ImageField(upload_to='static/img/images_counter/')),
                ('description_seccion2', models.CharField(max_length=9000)),
                ('width_image_seccion2', models.CharField(max_length=90)),
                ('height_image_seccion2', models.CharField(max_length=90)),
                ('padding_image_seccion2', models.CharField(max_length=90)),
                ('border_image_seccion2', models.CharField(max_length=90)),
                ('border_radius_image_seccion2', models.CharField(max_length=90)),
                ('seccion3_title', models.CharField(max_length=90)),
                ('seccion3_description', models.CharField(max_length=9000)),
                ('seccion4_title', models.CharField(max_length=90)),
                ('seccion4_description', models.CharField(max_length=9000)),
                ('for_page', models.CharField(max_length=30)),
            ],
        ),
    ]
