# Generated by Django 2.2 on 2019-04-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0011_auto_20190428_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='icono_plan',
            field=models.ImageField(upload_to='static/img/images_counter/'),
        ),
    ]
