# Generated by Django 2.2 on 2019-04-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0012_auto_20190428_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='font_family_description',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='font_family_title',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='height_icon',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='padding_icon',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='padding_text_description',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='padding_text_title',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='width_icon',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
