# Generated by Django 2.2 on 2019-04-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0013_auto_20190429_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='text_aling_description',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
