# Generated by Django 2.2 on 2019-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0014_plan_text_aling_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='text_aling_title',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
