# Generated by Django 2.2 on 2019-04-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0015_plan_text_aling_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color_background_caja_price',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='color_text_price',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='padding_price',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='price_plan',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='text_aling_price',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
