# Generated by Django 2.2 on 2019-04-30 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0017_auto_20190430_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='background_color_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='border_image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='border_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='border_radius_image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='border_radius_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='color_background_caja_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='color_text_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='font_family_description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='font_family_title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='height_image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='padding_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='padding_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='padding_text_title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='text_aling_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='text_aling_title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='width_image',
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_plan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_plan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
