# Generated by Django 2.2 on 2019-05-02 15:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0018_auto_20190430_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='background_color_caracteristica',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='background_color_contenedor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='border_caracteristica',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='border_image',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='border_radius_caracteristica',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='border_radius_image',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='caracteristicas_title',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='description_caracteristicas',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='font_family',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='font_size',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='height_contenedor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='height_image',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='image_caracteristica',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/images_counter/'),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='padding_caracteristica',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='width_image',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='background_color_contenedor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color_background_caja_description',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color_background_caja_texto',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='height_contenedor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='height_icon',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='icono_plan',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/images_counter/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='padding_icon',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='padding_text_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='text_aling_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='width_icon',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
