# Generated by Django 2.2 on 2019-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0019_auto_20190502_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='image_caracteristica',
            field=models.ImageField(blank=True, default=1, upload_to='static/img/images_counter/'),
            preserve_default=False,
        ),
    ]
