# Generated by Django 2.2 on 2019-05-06 15:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0021_auto_20190502_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios_publicidad_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', ckeditor.fields.RichTextField()),
                ('description_service', ckeditor.fields.RichTextField()),
                ('imagen', ckeditor.fields.RichTextField()),
                ('id_publicidad_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_pages.Publicidad_page')),
            ],
        ),
    ]
