# Generated by Django 2.2 on 2019-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0022_servicios_publicidad_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios_publicidad_page',
            name='imagen',
            field=models.ImageField(upload_to='static/img/images_page_publicidad/'),
        ),
    ]
