# Generated by Django 2.2 on 2019-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0023_auto_20190506_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios_publicidad_page',
            name='for_page',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
