# Generated by Django 2.2 on 2019-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0024_servicios_publicidad_page_for_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios_publicidad_page',
            name='color_background',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
