# Generated by Django 2.2 on 2019-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0025_servicios_publicidad_page_color_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad_page',
            name='descripcion_seccion_servicios',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicidad_page',
            name='title_seccion_servicios',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
