# Generated by Django 2.2 on 2019-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0026_auto_20190506_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios_publicidad_page',
            name='image_height',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicios_publicidad_page',
            name='image_width',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
