# Generated by Django 2.2 on 2019-05-06 17:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_pages', '0027_auto_20190506_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad_page',
            name='descripcion_seccion_servicios',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicidad_page',
            name='title_seccion_servicios',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
