# Generated by Django 2.1.7 on 2019-04-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=600)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='image_service',
            field=models.ImageField(upload_to='static/img/images_services/'),
        ),
        migrations.AlterField(
            model_name='service_plus',
            name='image_service',
            field=models.ImageField(upload_to='static/img/images_services/'),
        ),
    ]
