# Generated by Django 2.1.7 on 2019-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_auto_20190416_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cel_phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
