# Generated by Django 2.1.7 on 2019-04-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_auto_20190416_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=900)),
                ('image', models.ImageField(upload_to='static/img/images_about/')),
            ],
        ),
    ]
