# Generated by Django 2.2 on 2019-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_service',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service_plus',
            name='description_service',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='service_plus',
            name='name_service',
            field=models.CharField(max_length=500),
        ),
    ]
