# Generated by Django 2.2 on 2019-04-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_auto_20190417_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_frecuent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=600)),
                ('answer', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='img/images_ask_frecuent')),
            ],
        ),
    ]
