# Generated by Django 2.2 on 2019-04-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_ask_frecuent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_frecuent',
            name='image',
            field=models.ImageField(upload_to='static/img/images_ask_frecuent/'),
        ),
    ]
