# Generated by Django 2.2 on 2019-04-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_personalization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalization',
            old_name='image',
            new_name='image_fondo',
        ),
        migrations.AddField(
            model_name='personalization',
            name='image_transition',
            field=models.ImageField(default=1, upload_to='static/img/images_personalization/'),
            preserve_default=False,
        ),
    ]
