# Generated by Django 2.2 on 2019-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_auto_20190421_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='color_description',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization',
            name='color_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
