# Generated by Django 2.2 on 2019-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_auto_20190421_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='font_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
