# Generated by Django 2.2 on 2019-04-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0015_personalization_font_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='font_size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
