# Generated by Django 2.2 on 2019-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0016_personalization_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='background_color_text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization',
            name='border_radius_background',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
