# Generated by Django 2.2 on 2019-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0017_auto_20190421_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('image', models.ImageField(upload_to='static/img/images_team_freenet/')),
                ('description', models.CharField(max_length=9000)),
                ('profeccion', models.CharField(max_length=900)),
            ],
        ),
    ]
