# Generated by Django 2.2 on 2019-04-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0018_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color_background',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
