# Generated by Django 2.2 on 2019-04-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0019_service_color_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_plus',
            name='color_background',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
