# Generated by Django 2.2 on 2019-04-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0020_service_plus_color_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color_background',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
