# Generated by Django 2.2 on 2019-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0021_team_color_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('page_main', models.CharField(max_length=90)),
                ('copy', models.CharField(max_length=90)),
                ('schedule', models.CharField(max_length=200)),
            ],
        ),
    ]
