# Generated by Django 2.2 on 2019-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0022_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='color_background',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='color_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='font_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
