# Generated by Django 2.2 on 2019-04-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0023_auto_20190422_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='font_size',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
