# Generated by Django 2.2 on 2019-04-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0024_footer_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='celphone',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_address',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_celphone',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_city',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_copy',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_country',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_email',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_page',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_phone',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_schedule',
            field=models.ImageField(default=1, upload_to='static/img/images_footer/'),
            preserve_default=False,
        ),
    ]
