# Generated by Django 2.2 on 2019-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0025_auto_20190422_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_plus',
            name='image_height',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_plus',
            name='image_width',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
