# Generated by Django 2.2 on 2019-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0026_auto_20190422_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='icon_facebook',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='icon_instagram',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='icon_whatsapp',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='image_youtube',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
    ]
