# Generated by Django 2.2 on 2019-04-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0027_auto_20190423_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='image_youtube',
            new_name='icon_youtube',
        ),
    ]
