# Generated by Django 2.2 on 2019-04-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0028_auto_20190423_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='url_facebook',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='url_instagram',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='url_whatsapp',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='url_youtube',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='border_radius_image',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='height_image',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='width_image',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
