# Generated by Django 2.2 on 2019-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0030_auto_20190423_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='border',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='border_radius',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
