# Generated by Django 2.2 on 2019-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0031_auto_20190424_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='border',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='border_radius',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='color_text',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='font_size',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='padding',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text_transform',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
