# Generated by Django 2.2 on 2019-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0033_auto_20190424_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='font_family',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
