# Generated by Django 2.2 on 2019-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0034_service_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color_text',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='font_family',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='font_size',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='padding_text',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='text_aling',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='text_transform',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
