# Generated by Django 2.2 on 2019-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0035_auto_20190424_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='edad',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='habilidades',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='hobbies',
            field=models.CharField(default=1, max_length=9000),
            preserve_default=False,
        ),
    ]
