# Generated by Django 2.2 on 2019-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0036_auto_20190424_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='background_color_copy',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='padding_copy',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
