# Generated by Django 2.2 on 2019-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0037_auto_20190424_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image_customer', models.ImageField(upload_to='static/img/images_customers/')),
                ('description', models.CharField(max_length=9000)),
                ('email', models.CharField(max_length=100)),
                ('cel_phone', models.CharField(max_length=12)),
            ],
        ),
    ]
