# Generated by Django 2.2 on 2019-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0038_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='border',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='border_radius_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='height_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='with_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
