# Generated by Django 2.2 on 2019-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0039_auto_20190424_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='padding_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
