# Generated by Django 2.2 on 2019-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0040_customer_padding_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='margin_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
