# Generated by Django 2.2 on 2019-04-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0041_customer_margin_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personalization',
            new_name='Slider_setting',
        ),
    ]
