# Generated by Django 2.2 on 2019-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pagina', '0042_auto_20190425_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_setting',
            name='blur_radius_text_shadow',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider_setting',
            name='color_text_shadow',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider_setting',
            name='horizontal_text_shadow',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider_setting',
            name='vertical_text_shadow',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
