# Generated by Django 2.2 on 2019-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0044_footer_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='font_family_footer',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='font_size_footer',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='height_icon_copy',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='padding_icon_copy',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='width_icon_copy',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
