# Generated by Django 2.2 on 2019-04-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0046_auto_20190425_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='background_color_contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='border_contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='border_radius_contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='font_family_contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='font_size_contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='text_color_contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='text_contact',
        ),
    ]
