# Generated by Django 2.2 on 2019-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0048_auto_20190425_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='profeccion',
            new_name='height_text',
        ),
        migrations.AddField(
            model_name='team',
            name='profession',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='width_text',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
