# Generated by Django 2.2 on 2019-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0049_auto_20190425_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_description',
            field=models.CharField(default=1, max_length=90000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='icon1',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='icon2',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='icon3',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='icon4',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link_icon1',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link_icon2',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link_icon3',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link_icon4',
            field=models.ImageField(default=1, upload_to='static/img/images_social/'),
            preserve_default=False,
        ),
    ]
