# Generated by Django 2.2 on 2019-04-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0051_auto_20190425_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='image_page',
            new_name='image_logo_footer',
        ),
    ]
