# Generated by Django 2.2 on 2019-04-27 08:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0052_auto_20190426_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name_service'),
            preserve_default=False,
        ),
    ]
