# Generated by Django 2.2 on 2019-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0054_auto_20190427_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user_name',
            field=models.CharField(default=1, max_length=190),
            preserve_default=False,
        ),
    ]
