# Generated by Django 2.2 on 2019-04-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0055_team_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
