# Generated by Django 2.2 on 2019-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0056_remove_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_setting',
            name='blur_radius_text_shadow_description',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider_setting',
            name='color_text_shadow_description',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider_setting',
            name='horizontal_text_shadow_description',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider_setting',
            name='vertical_text_shadow_description',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
