# Generated by Django 2.2 on 2019-05-05 20:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0057_auto_20190505_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
