# Generated by Django 2.2 on 2019-05-06 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0058_auto_20190505_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_plus',
            name='description_service',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service_plus',
            name='name_service',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
