# Generated by Django 2.2 on 2019-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='static/img/logo/')),
                ('item1', models.CharField(max_length=30)),
                ('item2', models.CharField(max_length=30)),
                ('item3', models.CharField(max_length=30)),
                ('item4', models.CharField(max_length=30)),
                ('item5', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personalization_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='static/img/images_personalization/')),
                ('background_color', models.CharField(max_length=90)),
            ],
        ),
    ]
