# Generated by Django 2.2 on 2019-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_personalization_page_background_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalization_page',
            name='background_repeat',
        ),
    ]
