# Generated by Django 2.2 on 2019-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0003_remove_personalization_page_background_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalization_page',
            name='background_image',
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='background_repeat',
            field=models.CharField(choices=[('repeat', 'repeat'), ('no repeat', 'no repeat')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
