# Generated by Django 2.2 on 2019-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0004_auto_20190423_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='color_background',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
