# Generated by Django 2.2 on 2019-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0005_menu_color_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='width_image',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
