# Generated by Django 2.2 on 2019-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0006_menu_width_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item6',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
