# Generated by Django 2.2 on 2019-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0007_menu_item6'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='backgroun_color_item6',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='color_background_submenu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
