# Generated by Django 2.2 on 2019-04-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0008_auto_20190423_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='backgroun_color_item6',
            new_name='background_color_item6',
        ),
    ]
