# Generated by Django 2.2 on 2019-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0009_auto_20190423_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='background_color_item6_hover',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
