# Generated by Django 2.2 on 2019-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0010_menu_background_color_item6_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization_page',
            name='border',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='border_radius',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='color_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='float_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='font_family',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='font_family_title',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='text_aling',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='text_transform',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='title_1',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='title_2',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='title_3',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='title_4',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
