# Generated by Django 2.2 on 2019-04-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0011_auto_20190424_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalization_page',
            old_name='font_family',
            new_name='padding_text',
        ),
    ]
