# Generated by Django 2.2 on 2019-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0012_auto_20190424_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='color_text_menu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='color_text_submenu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
