# Generated by Django 2.2 on 2019-04-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0013_auto_20190424_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization_page',
            name='background_color_bar_customers',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
