# Generated by Django 2.2 on 2019-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0014_personalization_page_background_color_bar_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_background_color',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_border',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_border_radius',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_color_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_font_family',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_font_size',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_height',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_padding',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_services_professional',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_text_aling',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_area_width',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_background_color',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_border',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_border_radius',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_color_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_font_family',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_font_size',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_height',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_padding',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_text_aling',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='description_team_width',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
