# Generated by Django 2.2 on 2019-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0015_auto_20190425_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization_page',
            name='favicon',
            field=models.ImageField(default=1, upload_to='static/img/favicon/'),
            preserve_default=False,
        ),
    ]
