# Generated by Django 2.2 on 2019-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0016_personalization_page_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization_page',
            name='background_color_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='border_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='border_radius_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='font_family_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='font_size_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='text_color_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalization_page',
            name='text_contact',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
