# Generated by Django 2.2 on 2019-04-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0018_personalization_page_link_mape_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization_page',
            name='background_color_bar_team_redes',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
