# Generated by Django 2.2 on 2019-04-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0019_personalization_page_background_color_bar_team_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalization_page',
            name='description_area_services_professional',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='personalization_page',
            name='description_team',
            field=models.CharField(max_length=9000),
        ),
    ]
