# Generated by Django 2.2 on 2019-04-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0021_auto_20190426_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalization_page',
            name='description_area_services_professional',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='personalization_page',
            name='description_service',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='personalization_page',
            name='description_team',
            field=models.TextField(max_length=9000),
        ),
    ]
